//      methods.js        	   Structure-Activity Report JavaScript
//
//	24-sep-2010 (hf) open links in new window
//	22-jan-2009 (ac) added static reference to include flie
//  	01-dec-2008 (ac) created
//
// COPYRIGHT (C) 2008-2017 CHEMICAL COMPUTING GROUP ULC ("CCG").
// ALL RIGHTS RESERVED.
//
// ACCESS TO AND USE OF THIS SOFTWARE IS GOVERNED BY A SOFTWARE LICENSE
// AGREEMENT WITH CCG OR AN AUTHORIZED DISTRIBUTOR OF CCG.
//
// CCG DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
// ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, AND IN NO EVENT
// SHALL CCG BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
// ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
// IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
// OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

// -------------------------------- Kick Start --------------------------------

var methods_loaded = false;
var methods_XmlHttp;

function methods_Activate()
{
    if (methods_loaded) return null;

    return '<p><div id="methods_content"><p>The <i>Structure-Activity Report</i> is a collection of HTML, CSS,\n' +
	'JavaScript, Java and SD-files which have been generated by an SVL (Scientific\n' +
	'Vector Language) program, from within MOE<sup>TM</sup> (Molecular Operating\n' +
	'Environment), which is available from the <a \n' +
	'href="http://www.chemcomp.com" target="_blank">Chemical Computing Group, Inc</a>. The output\n' +
	'from this application may be viewed with any compatible browser, without having\n' +
	'MOE installed on the computer. Generating new or modified reports requires an\n' +
	'installation of MOE 2008 or later, with a valid license. The report can be\n' +
	'produced by configuring and executing the procedure using a panel within an\n' +
	'interactive session of MOE, or from a batch script, or from a MOE/web\n' +
	'application.\n' +
	'\n' +
	'<p>The algorithm used to detect and analyze scaffolds is described by <a \n' +
	'href="http://dx.doi.org/10.1021/jm801098a" target="_blank">[Clark &amp; Labute 2009]</a>. The analysis consists of the\n' +
	'following steps:\n' +
	'\n' +
	'<ol>\n' +
	'\n' +
	'<p><li>Gather the input materials, which consist of: a database of small\n' +
	'molecules, in MDL SD-file (.sdf) or MOE molecular database (.mdb)\n' +
	'format; optional specification of activity fields; optional specification of\n' +
	'scaffolds.\n' +
	'\n' +
	'<p><li>Calculate the fragmentation tree for the database, as described by\n' +
	'<a href="http://dx.doi.org/10.1021/ci600338x" target="_blank">[Schuffenhauer et al 2007]</a>.\n' +
	'\n' +
	'<p><li>If the scaffolds have not been completely supplied by the user,\n' +
	'automatically detect scaffolds which fit the dataset, with the assistance of the\n' +
	'previously calculated fragmentation tree.\n' +
	'\n' +
	'<p><li>If any of the scaffolds were calculated, or were incompletely annotated\n' +
	'with R-groups, find an optimal alignment of the scaffolds such that they share a\n' +
	'common numbering system.\n' +
	'\n' +
	'<p><li>Consider all of the possible substructure matches of each scaffold within\n' +
	'each input molecule, then find an optimal set of substructure matches so that\n' +
	'each molecule is assigned to exactly one scaffold in exactly one way, such that\n' +
	'the diversity of implied R-groups throughout the series is minimal.\n' +
	'\n' +
	'<p><li>Re-depict the scaffolds such that their atom-to-atom alignment is\n' +
	'represented by the corresponding 2D layout; depict all of the R-groups so that\n' +
	'their attachment points are consistently oriented; depict the input molecules\n' +
	'such that the layout of the scaffold substructure is the same for all, and the\n' +
	'substituents are decorated according to conventional aesthetics.\n' +
	'\n' +
	'<p><li>Extract the activity data, and produce various statistics, e.g. tables of\n' +
	'R-groups vs. scaffolds vs. activities; graphs of activities vs. calculated\n' +
	'properties; similarities of scaffolds and R-groups, etc.\n' +
	'\n' +
	'<p><li>Render all of the derived information as a single HTML page, which is\n' +
	'dependent only on static files stored in the same directory.\n' +
	'\n' +
	'</ol>\n' +
	'\n' +
	'<h2>References</h2>\n' +
	'\n' +
	'<table border="0" cellpadding="3">\n' +
	'\n' +
	'<tr><td valign="top"><nobr>[Clark &amp; Labute 2009]</nobr></td>\n' +
	'<td valign="top">\n' +
	'Clark, A.M., Labute, P.; Detection and Assignment of Common Scaffolds in\n' +
	'Project Databases of Lead Molecules; <i>Journal of Medicinal Chemistry</i>;\n' +
	'<b>52</b>, pp469-483 (2009).\n' +
	'<a href="http://dx.doi.org/10.1021/jm801098a" target="_blank">doi</a>.\n' +
	'</td></tr>\n' +
	'\n' +
	'<tr><td valign="top"><nobr>[Schuffenhauer et al 2007]</nobr></td>\n' +
	'<td valign="top">\n' +
	'Schuffenhauer, A., Ertl, P., Roggo, S., Wetzel, S., Koch, M.A., Waldmann, H.;\n' +
	'The Scaffold Tree - Visualization of the Scaffold Universe by Hierarchical\n' +
	'Scaffold Classification; <i>Journal of Chemical Information and Modeling</i>;\n' +
	'<b>47</b>, pp47-58 (2007).\n' +
	'<a href="http://dx.doi.org/10.1021/ci600338x" target="_blank">doi</a>\n' +
	'\n' +
	'</td></tr>\n' +
	'\n' +
	'</table></div>\n';
}

function methods_Deactivate()
{
}

